# Generated by Django 5.2.7 on 2025-11-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='approaved',
            new_name='approved',
        ),
    ]
